services:
  - type: web
    name: futurevisionmachines-website
    env: static
    buildCommand: echo "Static site - no build required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
